### ISSUE TITLE
kriteria lain yang diharapkan

### ISSUE THREAD

**Issue by AstriNovia** [vyatri/tln_app#6]
*kriteria lain yang diharapkan* belum dicantumin saat share data di WA

**Comment by vyatri** [comment]
![image from ios](https://user-images.githubusercontent.com/441413/52528258-c3d6c300-2d0c-11e9-88f5-3593cc5e67a6.jpg)

**Comment by vyatri** [comment]
@AstriNovia boleh tahu `berani` itu aslinya mau ngetik apa ya?

**Comment by vyatri** [comment]
kayaknya `kriteria lain yang diharapkan` itu `berani` deh. ada kata lain selain itu?
